# Generated by Django 4.1.3 on 2022-11-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_place_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='price',
            new_name='prices',
        ),
    ]
